terms:
    - id: 'Banana'
      term: 'Banana'
    - id: 'Barley'
      term: 'Barley'
    - id: 'Cashews'
      term: 'Cashews'
    - id: 'Cassava'
      term: 'Cassava'
    - id: 'Chick Pea'
      term: 'Chick Pea'
    - id: 'Cottonseed'
      term: 'Cottonseed'
    - id: 'Groundnut'
      term: 'Groundnut'
    - id: 'Maize'
      term: 'Maize'
    - id: 'Millet'
      term: 'Millet'
    - id: 'Pigeon Pea'
      term: 'Pigeon Pea'
    - id: 'Plantains'
      term: 'Plantains'
    - id: 'Rice'
      term: 'Rice'
    - id: 'Sesame'
      term: 'Sesame'
    - id: 'Sorghum'
      term: 'Sorghum'
    - id: 'Soybean'
      term: 'Soybean'
    - id: 'Sugarcane'
      term: 'Sugarcane'
    - id: 'Sweet Potato'
      term: 'Sweet Potato'
    - id: 'Tef'
      term: 'Tef'
    - id: 'Wheat'
      term: 'Wheat'
    - id: 'Yams'
      term: 'Yams'
