terms:
    - id: 'Angola'
      term: 'Angola'
    - id: 'Benin'
      term: 'Benin'
    - id: 'Botswana'
      term: 'Botswana'
    - id: 'Burkina Faso'
      term: 'Burkina Faso'
    - id: 'Burundi'
      term: 'Burundi'
    - id: 'Cameroon'
      term: 'Cameroon'
    - id: 'Central Africa'
      term: 'Central Africa'
    - id: 'Chad'
      term: 'Chad'
    - id: "Cote D'Ivoire"
      term: "Cote D'Ivoire"
    - id: 'Democratic Republic of the Congo'
      term: 'Democratic Republic of the Congo'
    - id: 'East Africa'
      term: 'East Africa'
    - id: 'Egypt'
      term: 'Egypt'
    - id: 'Eritrea'
      term: 'Eritrea'
    - id: 'Ethiopia'
      term: 'Ethiopia'
    - id: 'Gabon'
      term: 'Gabon'
    - id: 'Gambia'
      term: 'Gambia'
    - id: 'Ghana'
      term: 'Ghana'
    - id: 'Guinea'
      term: 'Guinea'
    - id: 'Kenya'
      term: 'Kenya'
    - id: 'Liberia'
      term: 'Liberia'
    - id: 'Madagascar'
      term: 'Madagascar'
    - id: 'Malawi'
      term: 'Malawi'
    - id: 'Mali'
      term: 'Mali'
    - id: 'Mauritania'
      term: 'Mauritania'
    - id: 'Mauritius'
      term: 'Mauritius'
    - id: 'Morocco'
      term: 'Morocco'
    - id: 'Mozambique'
      term: 'Mozambique'
    - id: 'Namibia'
      term: 'Namibia'
    - id: 'Niger'
      term: 'Niger'
    - id: 'Nigeria'
      term: 'Nigeria'
    - id: 'North Africa'
      term: 'North Africa'
    - id: 'Republic of the Congo'
      term: 'Republic of the Congo'
    - id: 'Rwanda'
      term: 'Rwanda'
    - id: 'Senegal'
      term: 'Senegal'
    - id: 'Sierra Leone'
      term: 'Sierra Leone'
    - id: 'Somalia'
      term: 'Somalia'
    - id: 'South Africa'
      term: 'South Africa'
    - id: 'Southern Africa'
      term: 'Southern Africa'
    - id: 'South Sudan'
      term: 'South Sudan'
    - id: 'Sudan'
      term: 'Sudan'
    - id: 'Tanzania'
      term: 'Tanzania'
    - id: 'Togo'
      term: 'Togo'
    - id: 'Uganda'
      term: 'Uganda'
    - id: 'West Africa'
      term: 'West Africa'
    - id: 'Zambia'
      term: 'Zambia'
    - id: 'Zimbabwe'
      term: 'Zimbabwe'
    - id: 'Other'
      term: 'Other'
