terms:
  - id: Annual Report
    term: Annual Report
  - id: Article
    term: Article
  - id: Audio
    term: Audio
  - id: Book/Book Chapter
    term: Book/Book Chapter
  - id: Capstone Project
    term: Capstone Project
  - id: Commissioned Report
    term: Commissioned Report
  - id: Conference Proceeding
    term: Conference Proceeding
  - id: Dataset
    term: Dataset
  - id: Dissertation
    term: Dissertation
  - id: Image
    term: Image
  - id: Journal
    term: Journal
  - id: Map or Cartographic Material
    term: Map or Cartographic Material
  - id: Masters Thesis
    term: Masters Thesis
  - id: Newsletter
    term: Newsletter
  - id: Part of Book
    term: Part of Book
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Project
    term: Project
  - id: Report
    term: Report
  - id: Research Paper
    term: Research Paper
  - id: Software or Program Code
    term: Software or Program Code
  - id: Spreadsheet
    term: Spreadsheet
  - id: Technical Document
    term: Technical Document
  - id: Video
    term: Video
  - id: White Paper
    term: White Paper
  - id: Other
    term: Other
