terms:
    - id: 'Aggregation, Quality, and Storage'
      term: 'Aggregation, Quality, and Storage'
    - id: 'Agribusiness'
      term: 'Agribusiness'
    - id: 'Agricultural Extension Services'
      term: 'Agricultural Extension Services'
    - id: 'Agronomics'
      term: 'Agronomics'
    - id: 'Crop/Livestock Improvement'
      term: 'Crop/Livestock Improvement'
    - id: 'Farm and Livestock Management'
      term: 'Farm and Livestock Management'
    - id: 'Farmer Cooperatives, Associations, and Organizations'
      term: 'Farmer Cooperatives, Associations, and Organizations'
    - id: 'Finance and Insurance'
      term: 'Finance and Insurance'
    - id: 'Infrastructure, Transport, and Logistics'
      term: 'Infrastructure, Transport, and Logistics'
    - id: 'Markets'
      term: 'Markets'
    - id: 'Pests and Diseases'
      term: 'Pests and Diseases'
    - id: 'Policies and Data'
      term: 'Policies and Data'
    - id: 'Processing'
      term: 'Processing'
    - id: 'Seed Systems'
      term: 'Seed Systems'
    - id: 'Soil, Fertilizer, and Other Input Systems'
      term: 'Soil, Fertilizer, and Other Input Systems'
