RAILS_ENV:              'development'
MAILER_HOST:            'http://agriknowledge-dev.library.cornell.edu'                # Example:  'my.example.org'
MAILER_PORT:            '25'

SOLR_URL:               'http://localhost:8983/solr/agra-kms'                   # Example:  'http://localhost:8983/solr/development'

FEDORA_ADMIN_USER:      'adminuser'
FEDORA_ADMIN_USER_PW:   'fedorauseradmin'
FEDORA_URL:             'http://localhost:8080/fedora/rest'                 # Example:  'http://localhost:8983/fedora/rest'

DATABASE_NAME_PREFIX:   'agrakms_dev'
DATABASE_RAILS_USER:    'agrakms_dba'
DATABASE_RAILS_USER_PW: '701wBx7017Im'
REDIS_HOST:             'localhost'

ADMIN_EMAIL:            'akiadmin@cornell.edu'
ADMIN_PASSWORD:         'agknosufia'

SECRET_KEY_BASE:        'bf13ce29491a6d729748d773a60f5bd72252087fd9d37c40a670d3fe66aea890a14408f245a315379c5bed9685218c248b21f9357f63b7512e50a132bf508208'
